# 2.2 Keras Deep Learning - RNN

#### 1. Import libraries
#### 2. Load data
#### 3. Wrangle data
#### 4. Creates Keras layered model

#### 1. Import Libraries

In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from numpy import unique
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers.core import Dense, Dropout

ModuleNotFoundError: No module named 'keras.layers.core'

In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [74]:
import keras
from keras.layers import Dense, Activation, Dropout, Reshape, Permute, Conv1D, MaxPooling1D

#### 2. Load data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
df=pd.read_csv('/content/drive/MyDrive/7 Machine Learning/Notebooks/Dataset-weather-cleaned.csv')

In [15]:
df.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [16]:
df.shape

(22950, 135)

In [8]:
dfa=pd.read_csv(('/content/drive/MyDrive/7 Machine Learning/Notebooks/climate_answers.csv'), index_col=0)

In [9]:
dfa.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [17]:
dfa.shape

(22950, 15)

#### 3. Wrangle data

In [85]:
# Turn X and y into arrays
X = np.array(X)
y = np.array(y)
X

array([[[  7.    ,   0.85  ,   1.018 , ...,   6.5   ,   0.8   ,
          10.9   ],
        [  1.    ,   0.81  ,   1.0195, ...,   3.7   ,  -0.9   ,
           7.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.4   ,  -0.4   ,
           5.1   ],
        ...,
        [  4.    ,   0.73  ,   1.0304, ...,  -5.9   ,  -8.5   ,
          -3.2   ],
        [  5.    ,   0.98  ,   1.0114, ...,   4.2   ,   2.2   ,
           4.9   ],
        [  5.    ,   0.88  ,   1.0003, ...,   8.5   ,   6.    ,
          10.9   ]],

       [[  6.    ,   0.84  ,   1.018 , ...,   6.1   ,   3.3   ,
          10.1   ],
        [  6.    ,   0.84  ,   1.0172, ...,   2.9   ,   2.2   ,
           4.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.3   ,   1.4   ,
           3.1   ],
        ...,
        [  6.    ,   0.97  ,   1.0292, ...,  -9.5   , -10.5   ,
          -8.5   ],
        [  5.    ,   0.62  ,   1.0114, ...,   4.    ,   3.    ,
           5.    ],
        [  7.    ,   0.91  ,   1.0007, ...,   8.9   ,   5.6   ,
          12.1   ]],

       [[  8.    ,   0.9   ,   1.018 , ...,   8.5   ,   5.1   ,
           9.9   ],
        [  6.    ,   0.77  ,   1.0179, ...,   3.1   ,  -0.5   ,
           6.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.7   ,   1.7   ,
           5.3   ],
        ...,
        [  8.    ,   0.93  ,   1.032 , ...,  -9.5   , -10.    ,
          -8.9   ],
        [  5.    ,   0.69  ,   1.0114, ...,   2.4   ,   1.3   ,
           4.1   ],
        [  7.    ,   0.91  ,   1.0096, ...,  10.5   ,   8.1   ,
          12.9   ]],

       ...,

       [[  4.    ,   0.76  ,   1.0227, ...,  16.7   ,  13.1   ,
          22.4   ],
        [  2.    ,   0.68  ,   1.0278, ...,  13.4   ,   8.6   ,
          18.2   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.3   ,   2.1   ,
           4.5   ],
        [  5.    ,   0.85  ,   1.0059, ...,  13.1   ,  12.1   ,
          14.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.8   ,   1.0212, ...,  15.4   ,  11.6   ,
          21.1   ],
        [  1.    ,   0.68  ,   1.0238, ...,  15.    ,   9.1   ,
          20.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.4   ,   2.7   ,
           4.1   ],
        [  5.    ,   0.94  ,   1.016 , ...,   7.5   ,   5.1   ,
          12.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.84  ,   1.0193, ...,  13.5   ,   9.9   ,
          19.2   ],
        [  4.    ,   0.68  ,   1.0235, ...,  14.4   ,  10.4   ,
          18.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  4.    ,   0.84  ,   1.0263, ...,   1.7   ,   0.7   ,
           2.7   ],
        [  5.    ,   0.97  ,   1.0164, ...,   9.7   ,   5.    ,
          12.6   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]]])

In [19]:
#Create an 'X' matrix
X = df
y = dfa
X

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.0180,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.0180,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.0180,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.0180,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.0180,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,0.79,1.0248,1.34,0.22,7.7,15.9,11.4,21.4,2,...,14.2,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22946,6,0.77,1.0244,1.34,0.22,5.4,16.7,14.3,21.9,0,...,14.3,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22947,4,0.76,1.0227,1.34,0.22,6.1,16.7,13.1,22.4,2,...,14.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22948,5,0.80,1.0212,1.34,0.22,5.8,15.4,11.6,21.1,1,...,12.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22949,5,0.84,1.0193,1.34,0.22,3.2,13.5,9.9,19.2,4,...,12.6,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5

In [86]:
X = X.reshape(-1,15,9)

In [87]:
X.shape

(22950, 15, 9)

In [88]:
y.shape

(22950, 15)

In [33]:
# import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler

In [89]:
#Split data into training and testing sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [91]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

In [92]:
X_train

array([[[  2.    ,   0.69  ,   1.0131, ...,  20.4   ,  13.6   ,
          26.9   ],
        [  3.    ,   0.53  ,   1.0132, ...,  22.5   ,  16.2   ,
          28.6   ],
        [  5.    ,   0.54  ,   1.0125, ...,  22.5   ,  18.6   ,
          27.1   ],
        ...,
        [  6.    ,   0.95  ,   1.029 , ...,   2.3   ,   0.8   ,
           3.8   ],
        [  5.    ,   0.48  ,   1.0192, ...,   8.5   ,   5.    ,
          11.9   ],
        [  6.    ,   0.83  ,   1.0082, ...,  15.6   ,  13.7   ,
          17.6   ]],

       [[  8.    ,   0.82  ,   1.0166, ...,  -1.8   ,  -3.2   ,
          -0.5   ],
        [  1.    ,   0.66  ,   1.0209, ...,  -3.6   ,  -6.    ,
           0.1   ],
        [  4.    ,   0.67  ,   1.017 , ...,  -3.3   ,  -7.2   ,
          -0.2   ],
        ...,
        [  3.    ,   0.67  ,   1.0327, ..., -17.4   , -19.2   ,
         -15.6   ],
        [  5.    ,   0.88  ,   1.0076, ...,  -6.9   ,  -9.4   ,
          -4.6   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  7.    ,   0.84  ,   1.0097, ...,  -1.8   ,  -6.    ,
           0.7   ],
        [  7.    ,   0.94  ,   1.0104, ...,   3.2   ,   1.6   ,
           6.7   ],
        [  6.    ,   0.67  ,   1.017 , ...,  -0.4   ,  -1.3   ,
           1.    ],
        ...,
        [  7.    ,   0.86  ,   1.0218, ..., -14.1   , -15.5   ,
         -12.7   ],
        [  7.    ,   0.77  ,   1.0134, ...,  -8.3   , -13.3   ,
          -5.5   ],
        [  5.    ,   0.9   ,   1.0186, ...,   1.    ,  -3.9   ,
           5.9   ]],

       ...,

       [[  6.    ,   0.82  ,   1.018 , ...,   6.3   ,   3.5   ,
          11.9   ],
        [  3.    ,   0.62  ,   1.0183, ...,  13.8   ,   7.6   ,
          21.    ],
        [  8.    ,   0.82  ,   1.0176, ...,   8.8   ,   7.5   ,
          11.7   ],
        ...,
        [  8.    ,   0.99  ,   1.0313, ...,  -7.7   ,  -9.7   ,
          -5.7   ],
        [  8.    ,   0.72  ,   1.0033, ...,   7.5   ,   5.4   ,
          10.    ],
        [  6.    ,   0.74  ,   1.023 , ...,   9.6   ,   7.8   ,
          11.5   ]],

       [[  7.    ,   0.7   ,   1.018 , ...,  10.1   ,   8.2   ,
          15.7   ],
        [  4.    ,   0.62  ,   1.0121, ...,  20.6   ,  17.    ,
          25.6   ],
        [  4.    ,   0.67  ,   1.017 , ...,  19.8   ,  16.4   ,
          24.3   ],
        ...,
        [  7.    ,   0.96  ,   1.0274, ...,  -3.5   ,  -8.    ,
           1.    ],
        [  8.    ,   0.78  ,   1.0121, ...,   8.6   ,   6.1   ,
          13.2   ],
        [  7.    ,   0.86  ,   1.0124, ...,  11.1   ,   8.5   ,
          13.7   ]],

       [[  6.    ,   0.68  ,   1.0195, ...,  11.6   ,   5.1   ,
          15.8   ],
        [  4.    ,   0.43  ,   1.0139, ...,  15.2   ,  10.9   ,
          22.2   ],
        [  4.    ,   0.48  ,   1.0134, ...,  13.2   ,  11.8   ,
          17.3   ],
        ...,
        [  8.    ,   0.99  ,   1.0339, ...,  -6.7   ,  -8.9   ,
          -4.4   ],
        [  6.    ,   0.48  ,   1.0148, ...,   1.    ,  -0.1   ,
           4.    ],
        [  7.    ,   0.8   ,   1.0242, ...,   9.6   ,   6.1   ,
          13.    ]]])

In [37]:
len(X_train[0])

15

In [38]:
len(X_train[0][0])

9

#### 4. Create Keras layered model

In [93]:
epochs = 10
batch_size = 16
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid')) #Don't use relu here!

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [94]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [95]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.0943 - loss: 9.1077 - val_accuracy: 0.0498 - val_loss: 8.4360
Epoch 2/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1153 - loss: 9.1948 - val_accuracy: 0.0342 - val_loss: 8.5126
Epoch 3/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.1346 - loss: 9.1778 - val_accuracy: 0.0303 - val_loss: 8.5298
Epoch 4/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.1924 - loss: 9.0983 - val_accuracy: 0.2712 - val_loss: 8.5302
Epoch 5/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.2562 - loss: 9.0496 - val_accuracy: 0.2623 - val_loss: 8.6347
Epoch 6/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.2447 - loss: 9.1630 - val_accuracy: 0.2795 - val_loss: 8.7095
Epoch 7/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.2638 - loss: 9.2859 - val_accuracy: 0.3055 - val_loss: 8.8356
Epoch 8/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.2850 - loss: 9.4581 - val_accuracy: 0.3076 - val_loss: 8.9366
Epoch 9/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.2940 - loss: 9.4869 - val_accuracy: 0.3111 - val_loss: 9.0457
Epoch 10/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.2921 - loss: 9.5898 - val_accuracy: 0.3088 - val_loss: 9.1768

#### create station names

In [96]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'

}

In [97]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [98]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step
Pred        BASEL  BELGRADE  MADRID
True
BASEL        1491         1    2190
BELGRADE      981         0     111
BUDAPEST      207         0       7
DEBILT         82         0       0
DUSSELDORF     28         0       1
HEATHROW       68         0      14
KASSEL         11         0       0
LJUBLJANA      52         0       9
MAASTRICHT      4         0       5
MADRID        177         0     281
MUNCHENB        7         0       1
OSLO            4         0       1
STOCKHOLM       4         0       0
VALENTIA        0         0       1

In [99]:
epochs = 20
batch_size = 16
n_hidden = 8

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid')) #Don't use relu here!

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [100]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [101]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.0497 - loss: 9.0345 - val_accuracy: 0.0891 - val_loss: 8.2081
Epoch 2/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.0837 - loss: 8.7404 - val_accuracy: 0.0793 - val_loss: 8.2596
Epoch 3/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.1387 - loss: 8.8195 - val_accuracy: 0.2151 - val_loss: 8.4544
Epoch 4/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1965 - loss: 8.9777 - val_accuracy: 0.3086 - val_loss: 8.6963
Epoch 5/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.2574 - loss: 9.3141 - val_accuracy: 0.3079 - val_loss: 8.9321
Epoch 6/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.2575 - loss: 9.5632 - val_accuracy: 0.3121 - val_loss: 9.1493
Epoch 7/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.2790 - loss: 9.6277 - val_accuracy: 0.3097 - val_loss: 9.3919
Epoch 8/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.2934 - loss: 10.1032 - val_accuracy: 0.3120 - val_loss: 9.5907
Epoch 9/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.2866 - loss: 10.1537 - val_accuracy: 0.3198 - val_loss: 9.7636
Epoch 10/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.3034 - loss: 10.3222 - val_accuracy: 0.3139 - val_loss: 9.9211
Epoch 11/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.3338 - loss: 10.6052 - val_accuracy: 0.3205 - val_loss: 10.1098
Epoch 12/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.3427 - loss: 10.7403 - val_accuracy: 0.3095 - val_loss: 10.2990
Epoch 13/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.3999 - loss: 10.9257 - val_accuracy: 0.3093 - val_loss: 10.4621
Epoch 14/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.4127 - loss: 11.1604 - val_accuracy: 0.3085 - val_loss: 10.6123
Epoch 15/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.4141 - loss: 11.1916 - val_accuracy: 0.3067 - val_loss: 10.7367
Epoch 16/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.4659 - loss: 11.3184 - val_accuracy: 0.6399 - val_loss: 10.8637
Epoch 17/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.4970 - loss: 11.4010 - val_accuracy: 0.6399 - val_loss: 10.9690
Epoch 18/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.5120 - loss: 11.5403 - val_accuracy: 0.6403 - val_loss: 11.0897
Epoch 19/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.5182 - loss: 11.9510 - val_accuracy: 0.6412 - val_loss: 11.2658
Epoch 20/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.5198 - loss: 11.9725 - val_accuracy: 0.6413 - val_loss: 11.3676

In [102]:
epochs = 20
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid')) #Don't use relu here!

In [103]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [104]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - accuracy: 0.1067 - loss: 9.7036 - val_accuracy: 0.0429 - val_loss: 8.5990
Epoch 2/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1751 - loss: 9.8052 - val_accuracy: 0.2623 - val_loss: 8.5561
Epoch 3/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.2707 - loss: 9.7884 - val_accuracy: 0.2720 - val_loss: 8.7723
Epoch 4/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.2689 - loss: 9.9189 - val_accuracy: 0.2853 - val_loss: 9.0548
Epoch 5/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.2869 - loss: 10.2452 - val_accuracy: 0.3055 - val_loss: 9.3614
Epoch 6/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.3208 - loss: 10.1767 - val_accuracy: 0.3069 - val_loss: 9.6736
Epoch 7/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.4043 - loss: 10.5126 - val_accuracy: 0.6433 - val_loss: 9.9774
Epoch 8/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.4975 - loss: 10.8132 - val_accuracy: 0.6438 - val_loss: 10.2259
Epoch 9/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.5465 - loss: 10.9880 - val_accuracy: 0.6417 - val_loss: 10.5026
Epoch 10/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.5742 - loss: 11.1684 - val_accuracy: 0.6434 - val_loss: 10.7461
Epoch 11/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6034 - loss: 11.4611 - val_accuracy: 0.6443 - val_loss: 11.0271
Epoch 12/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6078 - loss: 11.5842 - val_accuracy: 0.6420 - val_loss: 11.1642
Epoch 13/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.6264 - loss: 11.8189 - val_accuracy: 0.6398 - val_loss: 11.4362
Epoch 14/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6341 - loss: 12.1363 - val_accuracy: 0.6413 - val_loss: 11.7661
Epoch 15/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6394 - loss: 12.2486 - val_accuracy: 0.6419 - val_loss: 11.9713
Epoch 16/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6391 - loss: 12.4579 - val_accuracy: 0.6424 - val_loss: 12.2647
Epoch 17/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6356 - loss: 12.9887 - val_accuracy: 0.6419 - val_loss: 12.5088
Epoch 18/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6430 - loss: 13.2859 - val_accuracy: 0.6420 - val_loss: 12.7658
Epoch 19/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6421 - loss: 13.4222 - val_accuracy: 0.6433 - val_loss: 12.9760
Epoch 20/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6365 - loss: 13.6613 - val_accuracy: 0.6422 - val_loss: 13.1705

In [105]:
epochs = 30
batch_size = 16
n_hidden = 8

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid')) #Don't use relu here!

In [106]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [107]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.1008 - loss: 8.9957 - val_accuracy: 0.0791 - val_loss: 8.4125
Epoch 2/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.0986 - loss: 9.2634 - val_accuracy: 0.0749 - val_loss: 8.4091
Epoch 3/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.1605 - loss: 9.1712 - val_accuracy: 0.3086 - val_loss: 8.5508
Epoch 4/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.2421 - loss: 9.4528 - val_accuracy: 0.3071 - val_loss: 8.7888
Epoch 5/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.2720 - loss: 9.5483 - val_accuracy: 0.3125 - val_loss: 8.9958
Epoch 6/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.2699 - loss: 9.8882 - val_accuracy: 0.3163 - val_loss: 9.2207
Epoch 7/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.2779 - loss: 9.8846 - val_accuracy: 0.3106 - val_loss: 9.4735
Epoch 8/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.2823 - loss: 10.0498 - val_accuracy: 0.3116 - val_loss: 9.7158
Epoch 9/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.2870 - loss: 10.6218 - val_accuracy: 0.3125 - val_loss: 9.8851
Epoch 10/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.3000 - loss: 10.6866 - val_accuracy: 0.3083 - val_loss: 10.1084
Epoch 11/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.3298 - loss: 10.5836 - val_accuracy: 0.3099 - val_loss: 10.2495
Epoch 12/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.3451 - loss: 10.8222 - val_accuracy: 0.3095 - val_loss: 10.4401
Epoch 13/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.4155 - loss: 11.0592 - val_accuracy: 0.3083 - val_loss: 10.5933
Epoch 14/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.4145 - loss: 11.2323 - val_accuracy: 0.3060 - val_loss: 10.8018
Epoch 15/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.4112 - loss: 11.2325 - val_accuracy: 0.6427 - val_loss: 10.9806
Epoch 16/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.4748 - loss: 11.6508 - val_accuracy: 0.6401 - val_loss: 11.0991
Epoch 17/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.5104 - loss: 11.7783 - val_accuracy: 0.6413 - val_loss: 11.3024
Epoch 18/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.5030 - loss: 11.8014 - val_accuracy: 0.6405 - val_loss: 11.4445
Epoch 19/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.5139 - loss: 12.2795 - val_accuracy: 0.6384 - val_loss: 11.5440
Epoch 20/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.5073 - loss: 11.9569 - val_accuracy: 0.6403 - val_loss: 11.7378
Epoch 21/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step - accuracy: 0.5197 - loss: 12.1545 - val_accuracy: 0.6417 - val_loss: 11.8569
Epoch 22/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.5597 - loss: 12.4741 - val_accuracy: 0.6384 - val_loss: 11.9890
Epoch 23/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.5840 - loss: 12.6882 - val_accuracy: 0.6396 - val_loss: 12.1329
Epoch 24/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.5843 - loss: 12.9282 - val_accuracy: 0.6410 - val_loss: 12.2518
Epoch 25/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.5926 - loss: 13.0773 - val_accuracy: 0.6408 - val_loss: 12.3994
Epoch 26/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.5957 - loss: 12.9530 - val_accuracy: 0.6415 - val_loss: 12.5267
Epoch 27/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6023 - loss: 13.2494 - val_accuracy: 0.6408 - val_loss: 12.6323
Epoch 28/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6008 - loss: 13.0384 - val_accuracy: 0.6422 - val_loss: 12.7725
Epoch 29/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.5980 - loss: 13.2708 - val_accuracy: 0.6413 - val_loss: 12.9305
Epoch 30/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.5928 - loss: 13.5141 - val_accuracy: 0.6406 - val_loss: 13.0564

In [118]:
epochs = 20
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid')) #Don't use relu here!

In [119]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [120]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.0801 - loss: 10.0660 - val_accuracy: 0.2534 - val_loss: 8.6710
Epoch 2/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.2686 - loss: 10.5516 - val_accuracy: 0.2719 - val_loss: 9.2347
Epoch 3/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.2807 - loss: 10.9363 - val_accuracy: 0.2841 - val_loss: 9.9299
Epoch 4/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3954 - loss: 11.4205 - val_accuracy: 0.6392 - val_loss: 10.4511
Epoch 5/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 22s 11ms/step - accuracy: 0.5794 - loss: 11.8466 - val_accuracy: 0.6408 - val_loss: 10.9980
Epoch 6/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step - accuracy: 0.6319 - loss: 12.0094 - val_accuracy: 0.6408 - val_loss: 11.4173
Epoch 7/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.6329 - loss: 12.3529 - val_accuracy: 0.6399 - val_loss: 12.0444
Epoch 8/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 18s 9ms/step - accuracy: 0.6395 - loss: 13.0275 - val_accuracy: 0.6410 - val_loss: 12.4334
Epoch 9/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6459 - loss: 13.5086 - val_accuracy: 0.6412 - val_loss: 12.8049
Epoch 10/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.6356 - loss: 13.7019 - val_accuracy: 0.6408 - val_loss: 13.2172
Epoch 11/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6480 - loss: 14.0753 - val_accuracy: 0.6431 - val_loss: 13.7118
Epoch 12/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6471 - loss: 14.3197 - val_accuracy: 0.6420 - val_loss: 12.4573
Epoch 13/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.6506 - loss: 14.0515 - val_accuracy: 0.6412 - val_loss: 13.2030
Epoch 14/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.6404 - loss: 14.2704 - val_accuracy: 0.6415 - val_loss: 13.8076
Epoch 15/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6452 - loss: 14.7267 - val_accuracy: 0.6415 - val_loss: 14.2602
Epoch 16/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - accuracy: 0.6458 - loss: 15.1821 - val_accuracy: 0.6419 - val_loss: 14.6334
Epoch 17/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.6452 - loss: 15.7046 - val_accuracy: 0.6419 - val_loss: 14.8338
Epoch 18/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 19s 9ms/step - accuracy: 0.6466 - loss: 15.6726 - val_accuracy: 0.6422 - val_loss: 15.1260
Epoch 19/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - accuracy: 0.6465 - loss: 15.7418 - val_accuracy: 0.6412 - val_loss: 15.5912
Epoch 20/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6471 - loss: 16.3075 - val_accuracy: 0.6415 - val_loss: 15.8584

In [ ]:
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))

In [114]:
epochs = 20
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim), return_sequences=True)) # Added return_sequences=True
model.add(Dropout(0.5))
model.add(Conv1D(n_hidden, kernel_size=2, activation='sigmoid')) # Removed redundant input_shape
model.add(MaxPooling1D())
model.add(Flatten()) # Added Flatten layer
model.add(Dense(n_classes, activation='sigmoid')) #Don't use relu here!

In [115]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [75]:

from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D

In [116]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.1956 - loss: 9.7372 - val_accuracy: 0.3194 - val_loss: 12.7515
Epoch 2/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.3195 - loss: 14.0190 - val_accuracy: 0.3207 - val_loss: 16.5303
Epoch 3/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3249 - loss: 17.9670 - val_accuracy: 0.3250 - val_loss: 18.9675
Epoch 4/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.3234 - loss: 20.7215 - val_accuracy: 0.3236 - val_loss: 22.5631
Epoch 5/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.3221 - loss: 24.4712 - val_accuracy: 0.3200 - val_loss: 26.0344
Epoch 6/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.3205 - loss: 27.8946 - val_accuracy: 0.3093 - val_loss: 28.9657
Epoch 7/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.3131 - loss: 30.2314 - val_accuracy: 0.3226 - val_loss: 31.9680
Epoch 8/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.3123 - loss: 33.5412 - val_accuracy: 0.3201 - val_loss: 34.9343
Epoch 9/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.3128 - loss: 37.0442 - val_accuracy: 0.3142 - val_loss: 38.2519
Epoch 10/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3141 - loss: 40.5216 - val_accuracy: 0.3076 - val_loss: 41.3214
Epoch 11/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.3137 - loss: 42.8470 - val_accuracy: 0.3133 - val_loss: 44.6302
Epoch 12/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - accuracy: 0.3145 - loss: 48.5186 - val_accuracy: 0.3153 - val_loss: 48.0254
Epoch 13/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3155 - loss: 51.1671 - val_accuracy: 0.3062 - val_loss: 51.4368
Epoch 14/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.3103 - loss: 53.1508 - val_accuracy: 0.3127 - val_loss: 55.1145
Epoch 15/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.3126 - loss: 58.4727 - val_accuracy: 0.3071 - val_loss: 57.7914
Epoch 16/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.3129 - loss: 61.5760 - val_accuracy: 0.3120 - val_loss: 60.7387
Epoch 17/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3132 - loss: 64.6852 - val_accuracy: 0.3160 - val_loss: 64.7804
Epoch 18/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.3732 - loss: 66.9413 - val_accuracy: 0.3175 - val_loss: 66.6163
Epoch 19/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.4508 - loss: 69.9367 - val_accuracy: 0.6417 - val_loss: 70.2149
Epoch 20/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6456 - loss: 75.9690 - val_accuracy: 0.6417 - val_loss: 74.4281

In [131]:
epochs = 20
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='tanh')) #Don't use relu here!

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [132]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [133]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.0362 - loss: 24.0057 - val_accuracy: 0.0150 - val_loss: 25.1848
Epoch 2/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.1532 - loss: 23.8653 - val_accuracy: 0.1873 - val_loss: 25.1135
Epoch 3/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1996 - loss: 22.9642 - val_accuracy: 0.0167 - val_loss: 23.0554
Epoch 4/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1102 - loss: 24.1701 - val_accuracy: 0.0112 - val_loss: 23.8951
Epoch 5/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.0938 - loss: 23.6997 - val_accuracy: 0.0756 - val_loss: 22.2996
Epoch 6/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.0807 - loss: 25.9197 - val_accuracy: 0.0183 - val_loss: 25.3845
Epoch 7/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.0899 - loss: 25.6803 - val_accuracy: 0.1386 - val_loss: 21.5911
Epoch 8/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.0951 - loss: 24.6813 - val_accuracy: 0.1575 - val_loss: 19.0426
Epoch 9/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.0842 - loss: 24.5230 - val_accuracy: 0.1896 - val_loss: 19.1335
Epoch 10/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1020 - loss: 23.6778 - val_accuracy: 0.1903 - val_loss: 25.1468
Epoch 11/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 19s 8ms/step - accuracy: 0.1136 - loss: 24.5931 - val_accuracy: 0.1903 - val_loss: 19.8870
Epoch 12/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.1039 - loss: 25.0975 - val_accuracy: 0.1894 - val_loss: 20.1979
Epoch 13/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step - accuracy: 0.1034 - loss: 24.2199 - val_accuracy: 0.1903 - val_loss: 24.6291
Epoch 14/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1179 - loss: 25.0737 - val_accuracy: 0.1901 - val_loss: 26.6947
Epoch 15/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.1120 - loss: 24.6149 - val_accuracy: 0.1901 - val_loss: 28.8257
Epoch 16/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - accuracy: 0.1086 - loss: 24.6463 - val_accuracy: 0.1879 - val_loss: 24.6040
Epoch 17/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.1009 - loss: 23.5764 - val_accuracy: 0.1896 - val_loss: 21.2090
Epoch 18/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.1206 - loss: 24.5965 - val_accuracy: 0.1887 - val_loss: 25.4393
Epoch 19/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1260 - loss: 25.1248 - val_accuracy: 0.1901 - val_loss: 27.7624
Epoch 20/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1003 - loss: 26.0794 - val_accuracy: 0.1901 - val_loss: 23.4175

In [126]:
epochs = 30
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = y_train.shape[1]

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid')) #Don't use relu here!

In [127]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [128]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.0791 - loss: 9.6985 - val_accuracy: 0.1806 - val_loss: 8.6640
Epoch 2/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.1900 - loss: 10.0163 - val_accuracy: 0.2785 - val_loss: 8.8207
Epoch 3/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.2778 - loss: 10.2020 - val_accuracy: 0.3034 - val_loss: 9.1687
Epoch 4/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.2880 - loss: 10.6140 - val_accuracy: 0.3086 - val_loss: 9.4856
Epoch 5/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.2852 - loss: 10.6059 - val_accuracy: 0.3067 - val_loss: 9.8511
Epoch 6/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.3135 - loss: 10.8517 - val_accuracy: 0.3067 - val_loss: 10.1772
Epoch 7/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.3813 - loss: 10.9562 - val_accuracy: 0.3081 - val_loss: 10.4615
Epoch 8/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.4622 - loss: 11.4226 - val_accuracy: 0.6401 - val_loss: 10.7649
Epoch 9/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.5355 - loss: 11.5637 - val_accuracy: 0.6413 - val_loss: 10.9973
Epoch 10/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.5576 - loss: 11.9264 - val_accuracy: 0.6412 - val_loss: 11.3390
Epoch 11/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.5918 - loss: 12.2055 - val_accuracy: 0.6405 - val_loss: 11.6586
Epoch 12/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6039 - loss: 12.3719 - val_accuracy: 0.6415 - val_loss: 11.8744
Epoch 13/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6261 - loss: 12.6039 - val_accuracy: 0.6429 - val_loss: 12.1062
Epoch 14/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6198 - loss: 12.9299 - val_accuracy: 0.6415 - val_loss: 12.3664
Epoch 15/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6244 - loss: 12.8644 - val_accuracy: 0.6427 - val_loss: 10.9848
Epoch 16/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6302 - loss: 12.7749 - val_accuracy: 0.6417 - val_loss: 11.7627
Epoch 17/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6342 - loss: 13.2955 - val_accuracy: 0.6403 - val_loss: 12.1623
Epoch 18/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6406 - loss: 13.7543 - val_accuracy: 0.6419 - val_loss: 12.5515
Epoch 19/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6420 - loss: 13.8904 - val_accuracy: 0.6408 - val_loss: 12.7269
Epoch 20/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6398 - loss: 14.0169 - val_accuracy: 0.6422 - val_loss: 12.8577
Epoch 21/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6371 - loss: 14.1291 - val_accuracy: 0.6420 - val_loss: 12.9834
Epoch 22/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6425 - loss: 14.3430 - val_accuracy: 0.6420 - val_loss: 13.1390
Epoch 23/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6433 - loss: 14.2531 - val_accuracy: 0.6417 - val_loss: 13.2899
Epoch 24/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6418 - loss: 14.2967 - val_accuracy: 0.6419 - val_loss: 13.3325
Epoch 25/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6438 - loss: 14.1947 - val_accuracy: 0.6417 - val_loss: 13.4123
Epoch 26/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6455 - loss: 14.2978 - val_accuracy: 0.6429 - val_loss: 13.3761
Epoch 27/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6454 - loss: 14.0267 - val_accuracy: 0.6413 - val_loss: 13.4912
Epoch 28/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6486 - loss: 14.4186 - val_accuracy: 0.6413 - val_loss: 13.6255
Epoch 29/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6408 - loss: 14.3650 - val_accuracy: 0.6420 - val_loss: 13.7753
Epoch 30/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6488 - loss: 14.5670 - val_accuracy: 0.6419 - val_loss: 13.8738

In [129]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [130]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BELGRADE  MADRID
True
BASEL        3675         1       6
BELGRADE     1089         0       3
BUDAPEST      214         0       0
DEBILT         82         0       0
DUSSELDORF     29         0       0
HEATHROW       81         0       1
KASSEL         11         0       0
LJUBLJANA      61         0       0
MAASTRICHT      9         0       0
MADRID        449         1       8
MUNCHENB        8         0       0
OSLO            5         0       0
STOCKHOLM       4         0       0
VALENTIA        1         0       0